name: workflow-artifacts
on:
  push:

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 - Checkout
        uses: actions/checkout@v6
      - name: Step-3
        run: |
          echo `pwd` >> my-artifact.txt
          mkdir -p artifacts
          hostname >> artifacts/hostname.txt
          ls -ltr
          hostname
      - name: Step-4 - Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: single_file
          path: my-artifact.txt
      - name: Upload from directory
        uses: actions/upload-artifact@v7
        with:
          name: directory_artifact
          path: artifacts/
      - name: Upload multiple paths with exclusions
        uses: actions/upload-artifact@v7
        with:
          name: multiple_paths_with_exclusions
          path: |
            ./my-artifact.txt
            artifacts/
            !**/hostname.txt
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: checking current directory
        run: |
          pwd
          ls -ltr
      - name: Downloading single file artifact
        uses: actions/download-artifact@v8
        with:
          name: single_file
      - name: checking directory post download
        run: |
          pwd
          ls -ltr
